const KEY='linhas_erick_v7',CFG='linhas_erick_cfg_v7',NOT='linhas_erick_notify_v7';
let data=JSON.parse(localStorage.getItem(KEY)||'null')||window.DEFAULT_CLIENTS,openId=null;
let firebaseApp=null,firebaseAuth=null,firebaseDb=null,firebaseUser=null;
function g(i){return document.getElementById(i)}function n(v){v=Number(v);return isFinite(v)?v:0}function br(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n(v))}
function rec(x){return Math.max(0,n(x.base)-n(x.desc))}function cus(x){return Math.max(0,n(x.custo)-n(x.abat))}function luc(x){return rec(x)-cus(x)}function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pad2(v){return String(v).padStart(2,'0')}function today(){let d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}function dateKey(d){return d?d.getFullYear()+'-'+pad2(d.getMonth()+1)+'-'+pad2(d.getDate()):''}
function daysInMonth(y,m){return new Date(y,m,0).getDate()}function formatDate(d){return d?pad2(d.getDate())+'/'+pad2(d.getMonth()+1)+'/'+d.getFullYear():'-'}function diffDays(a,b){return Math.round((new Date(a.getFullYear(),a.getMonth(),a.getDate())-new Date(b.getFullYear(),b.getMonth(),b.getDate()))/86400000)}
function dueDateInMonth(x,off=0){let d=n(x.v);if(!d)return null;let now=today(),y=now.getFullYear(),m=now.getMonth()+1+off;while(m>12){m-=12;y++}while(m<1){m+=12;y--}return new Date(y,m-1,Math.min(d,daysInMonth(y,m)))}
function paidThisMonth(x){if(x.pago!='Pago')return false;if(!x.dataPg)return true;let d=new Date(x.dataPg+'T00:00:00'),now=today();return d.getFullYear()==now.getFullYear()&&d.getMonth()==now.getMonth()}
function realDueDate(x){if(x.status!='Cliente ativo')return null;return paidThisMonth(x)?dueDateInMonth(x,1):dueDateInMonth(x,0)}
function due(x){let d=realDueDate(x);return x.status=='Cliente ativo'&&x.pago!='Pago'&&dateKey(d)==dateKey(today())}function late(x){let d=realDueDate(x);return x.status=='Cliente ativo'&&x.pago!='Pago'&&d&&diffDays(d,today())<0}
function phone(x){let d=String(x.wa||x.num||'').replace(/\D/g,'');if(!d)return'';if(d.length==10||d.length==11)d='55'+d;return d}
function saveCfg(){localStorage.setItem(CFG,JSON.stringify({pixE:g('pixE').value,pixT:g('pixT').value,msgCob:g('msgCob').value,msgObg:g('msgObg').value}))}
function loadCfg(){let c=JSON.parse(localStorage.getItem(CFG)||'{}');['pixE','pixT','msgCob','msgObg'].forEach(i=>{if(c[i])g(i).value=c[i]})}
function msg(x,t){let m=t=='obg'?g('msgObg').value:g('msgCob').value;return m.replaceAll('{cliente}',x.cliente||x.resp||'cliente').replaceAll('{operadora}',x.op||'').replaceAll('{valor_base}',br(x.base)).replaceAll('{desconto}',br(x.desc)).replaceAll('{valor_final}',br(rec(x))).replaceAll('{pix_email}',g('pixE').value).replaceAll('{pix_telefone}',g('pixT').value).replaceAll('{vencimento}',x.v||'')}
function zap(id,t='cob'){let x=data.find(a=>a.id==id),p=phone(x);if(!p)return alert('Sem número/WhatsApp válido.');window.open('https://wa.me/'+p+'?text='+encodeURIComponent(msg(x,t)),'_blank')}
function paid(id){let x=data.find(a=>a.id==id);if(confirm('Confirmar pagamento de '+(x.cliente||x.resp)+'?')){x.pago='Pago';x.dataPg=new Date().toISOString().slice(0,10);save();render();if(confirm('Abrir agradecimento?'))zap(id,'obg')}}
function pend(id){let x=data.find(a=>a.id==id);x.pago='Pendente';x.dataPg='';save();render()}function del(id){let x=data.find(a=>a.id==id);if(confirm('Apagar '+(x.cliente||x.resp||x.num)+'?')){data=data.filter(a=>a.id!=id);save();render()}}
function add(){let id=Math.max(0,...data.map(x=>n(x.id)))+1;data.unshift({id,v:pad2(new Date().getDate()),op:'TIM',num:'',wa:'',resp:'',cpf:'',nasc:'',senha:'',cliente:'',base:80,desc:0,custo:30,abat:0,status:'Cliente ativo',pago:'Pendente',dataPg:'',obs:''});openId=id;save();render()}
function upd(id,k,v){let x=data.find(a=>a.id==id);x[k]=['base','desc','custo','abat'].includes(k)?n(v):v;save();render(false)}function edit(id){openId=openId==id?null:id;render(false)}
function filt(){let q=g('q').value.toLowerCase(),op=g('fOp').value,st=g('fSt').value,pg=g('fPg').value;return data.filter(x=>{let tx=Object.values(x).join(' ').toLowerCase();return(!q||tx.includes(q))&&(!op||x.op==op)&&(!st||x.status==st)&&(!pg||x.pago==pg)}).sort((a,b)=>(realDueDate(a)||new Date(2999,1,1))-(realDueDate(b)||new Date(2999,1,1))||String(a.cliente).localeCompare(b.cliente))}
function field(x,k,l,type='text'){return `<div><label>${l}</label><input type="${type}" value="${esc(x[k])}" onchange="upd(${x.id},'${k}',this.value)"></div>`}function sel(x,k,l,arr){return `<div><label>${l}</label><select onchange="upd(${x.id},'${k}',this.value)">${arr.map(o=>`<option ${x[k]==o?'selected':''}>${o}</option>`).join('')}</select></div>`}
function mini(x){let d=realDueDate(x),dd=d?diffDays(d,today()):0,info=dd<0?`${Math.abs(dd)} dia(s) atrasado`:dd==0?'vence hoje':`vence em ${dd} dia(s)`;return `<div class=item><b>${esc(x.cliente||x.resp)}</b><div class=hint>${esc(x.op)} • ${br(rec(x))} • ${formatDate(d)} • ${info}</div><div class=actions><button class=zap onclick="zap(${x.id})">Cobrar</button><button class=ok onclick="paid(${x.id})">Pago</button></div></div>`}
function render(){save();let tr=0,tc=0,tl=0;data.forEach(x=>{tr+=rec(x);tc+=cus(x);tl+=luc(x)});g('tRec').textContent=br(tr);g('tCus').textContent=br(tc);g('tLuc').textContent=br(tl);g('tLuc').className=tl<0?'neg':'pos';g('tLin').textContent=data.length;monthly();
let ds=data.filter(due).sort((a,b)=>realDueDate(a)-realDueDate(b)),ls=data.filter(late).sort((a,b)=>realDueDate(a)-realDueDate(b)),ns=data.filter(x=>x.status=='Cliente ativo'&&!due(x)&&!late(x)).sort((a,b)=>realDueDate(a)-realDueDate(b)).slice(0,20);
g('late').innerHTML=ls.length?`<button class=zap onclick="lsCharge()">Cobrar atrasados</button>`+ls.map(mini).join(''):'<div class=hint>Nenhum cliente atrasado.</div>';g('due').innerHTML=ds.length?`<button class=zap onclick="dueCharge()">Cobrar todos de hoje</button>`+ds.map(mini).join(''):'<div class=hint>Nenhum cliente pendente vence hoje.</div>';g('nextDue').innerHTML=ns.length?ns.map(mini).join(''):'<div class=hint>Nenhum próximo vencimento.</div>';
g('list').innerHTML=filt().map(x=>{let l=luc(x),d=realDueDate(x);return `<div class=item><div class=title><div><b>${esc(x.cliente||x.resp||'Sem nome')}</b><div class=hint>${esc(x.num||'sem número')}${x.wa?' • WhatsApp '+esc(x.wa):''}</div></div><div><span class=badge>${esc(x.op)}</span><span class="badge ${x.pago=='Pago'?'pago':'pend'}">${x.pago}</span>${late(x)?'<span class="badge late">Atrasado</span>':''}</div></div><div class="row grid"><div><span class=hint>Próx. venc.</span><br><b>${formatDate(d)}</b></div><div><span class=hint>Base</span><br><b>${br(x.base)}</b></div><div><span class=hint>Desconto</span><br><b>${br(x.desc)}</b></div><div><span class=hint>A pagar</span><br><b>${br(rec(x))}</b></div><div><span class=hint>Custo</span><br><b>${br(cus(x))}</b></div><div><span class=hint>Lucro</span><br><b class=${l<0?'neg':'pos'}>${br(l)}</b></div></div><div class="actions grid"><button onclick="edit(${x.id})">Editar</button><button class=zap onclick="zap(${x.id})">Cobrar</button>${x.pago=='Pago'?`<button class=sec onclick="pend(${x.id})">Pendente</button>`:`<button class=ok onclick="paid(${x.id})">Pago</button>`}<button class=del onclick="del(${x.id})">Apagar</button></div><div class="edit ${openId==x.id?'open':''}"><div class="row grid">${field(x,'v','Vencimento')}${sel(x,'op','Operadora',['TIM','VIVO','CLARO','SEM OPERADORA'])}${field(x,'num','Número')}${field(x,'wa','WhatsApp')}${field(x,'resp','Responsável')}${field(x,'cpf','CPF')}${field(x,'nasc','Nascimento')}${field(x,'senha','Senha')}${field(x,'cliente','Cliente')}${field(x,'base','Base','number')}${field(x,'desc','Desconto','number')}${field(x,'custo','Custo','number')}${field(x,'abat','Abatimento','number')}${sel(x,'status','Status',['Cliente ativo','Uso próprio','Linha parada','Custo interno'])}${sel(x,'pago','Pagamento',['Pendente','Pago'])}${field(x,'dataPg','Data Pg')}</div><label>Obs</label><textarea onchange="upd(${x.id},'obs',this.value)">${esc(x.obs)}</textarea></div></div>`}).join('')}
function monthly(){let now=new Date(),key=now.getFullYear()+'-'+pad2(now.getMonth()+1),prev=0,recv=0,falt=0,cost=0,pagos=0,pend=0;data.forEach(x=>{if(['Cliente ativo','Uso próprio','Linha parada','Custo interno'].includes(x.status))cost+=cus(x);if(x.status=='Cliente ativo'){prev+=rec(x);let pg=x.dataPg?x.dataPg.slice(0,7):'';if(x.pago=='Pago'&&pg==key){recv+=rec(x);pagos++}else{falt+=rec(x);pend++}}});let meses=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];g('mesTitulo').textContent='Resumo de '+meses[now.getMonth()]+'/'+now.getFullYear();g('mPrevista').textContent=br(prev);g('mRecebida').textContent=br(recv);g('mFalta').textContent=br(falt);g('mCusto').textContent=br(cost);g('mLucroPrev').textContent=br(prev-cost);g('mLucroReal').textContent=br(recv-cost);g('mPagos').textContent=pagos;g('mPendentes').textContent=pend}
function dueCharge(){data.filter(due).forEach(x=>zap(x.id))}function lsCharge(){data.filter(late).forEach(x=>zap(x.id))}
function csv(){let h=['Venc','Operadora','Numero','WhatsApp','Responsavel','CPF','Nascimento','Senha','Cliente','Base','Desconto','A pagar','Custo','Abat','Custo real','Lucro','Status','Pago','DataPg','Obs'];let rows=data.map(x=>[x.v,x.op,x.num,x.wa,x.resp,x.cpf,x.nasc,x.senha,x.cliente,x.base,x.desc,rec(x),x.custo,x.abat,cus(x),luc(x),x.status,x.pago,x.dataPg,x.obs]);download('controle_linhas_v7.csv',[h,...rows].map(r=>r.map(c=>`"${String(c??'').replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv')}
function backupJSON(){download('backup_controle_linhas_v7.json',JSON.stringify({data,cfg:JSON.parse(localStorage.getItem(CFG)||'{}')},null,2),'application/json')}function fecharMes(){let txt='Resumo mensal gerado em '+new Date().toLocaleString('pt-BR');download('resumo_mensal.txt',txt,'text/plain')}
function download(name,txt,type){let b=new Blob([txt],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function initFirebase(){if(firebaseApp)return true;try{firebaseApp=firebase.initializeApp(window.FIREBASE_CONFIG);firebaseAuth=firebase.auth();firebaseDb=firebase.firestore();firebaseAuth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);firebaseAuth.onAuthStateChanged(u=>{firebaseUser=u;g('cloudStatus').textContent=u?'Logado: '+(u.email||'Google'):'Firebase pronto'});return true}catch(e){alert('Erro Firebase: '+e.message);return false}}
async function googleLogin(){try{initFirebase();let p=new firebase.auth.GoogleAuthProvider();try{await firebaseAuth.signInWithPopup(p)}catch(e){await firebaseAuth.signInWithRedirect(p)}}catch(e){alert('Erro login: '+e.message)}}
function doc(){if(!firebaseUser)throw Error('Faça login primeiro');return firebaseDb.collection('usuarios').doc(firebaseUser.uid).collection('controle').doc('principal')}
async function cloudSave(){try{initFirebase();if(!firebaseUser)return alert('Faça login primeiro');await doc().set({data,cfg:JSON.parse(localStorage.getItem(CFG)||'{}'),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});alert('Salvo na nuvem')}catch(e){alert('Erro salvar: '+e.message)}}
async function cloudLoad(){try{initFirebase();if(!firebaseUser)return alert('Faça login primeiro');let s=await doc().get();if(!s.exists)return alert('Nada na nuvem');let o=s.data();data=o.data||data;localStorage.setItem(KEY,JSON.stringify(data));if(o.cfg)localStorage.setItem(CFG,JSON.stringify(o.cfg));loadCfg();render();alert('Carregado da nuvem')}catch(e){alert('Erro carregar: '+e.message)}}
function notifyOn(){if(!('Notification'in window))return alert('Sem suporte');Notification.requestPermission().then(p=>alert(p=='granted'?'Avisos permitidos':'Permissão negada'))}
function tests(){console.assert(rec({base:80,desc:5})==75);console.assert(cus({custo:30,abat:10})==20);console.assert(data.length>=30);console.log('V7 OK')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.log);
loadCfg();initFirebase();render();tests();