window.DEFAULT_CLIENTS = [
  {
    "id": 1,
    "v": "01",
    "op": "TIM",
    "num": "19981092980",
    "wa": "",
    "resp": "Nerias",
    "cpf": "",
    "nasc": "",
    "senha": "3030",
    "cliente": "Nerias",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 2,
    "v": "01",
    "op": "TIM",
    "num": "19982604231",
    "wa": "",
    "resp": "Maria",
    "cpf": "",
    "nasc": "",
    "senha": "1733",
    "cliente": "Fabiano",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 3,
    "v": "01",
    "op": "TIM",
    "num": "19981667252",
    "wa": "",
    "resp": "Thiago",
    "cpf": "",
    "nasc": "",
    "senha": "4796",
    "cliente": "Thiago",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 4,
    "v": "10",
    "op": "TIM",
    "num": "19981187881",
    "wa": "",
    "resp": "Dirceu",
    "cpf": "",
    "nasc": "",
    "senha": "5758",
    "cliente": "Dora",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 5,
    "v": "10",
    "op": "TIM",
    "num": "19981678522",
    "wa": "",
    "resp": "Francisco",
    "cpf": "",
    "nasc": "",
    "senha": "0225",
    "cliente": "Giovanni",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 6,
    "v": "10",
    "op": "TIM",
    "num": "19981039093",
    "wa": "",
    "resp": "Daniel",
    "cpf": "",
    "nasc": "",
    "senha": "4077",
    "cliente": "Érica",
    "base": 80,
    "desc": 0,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 7,
    "v": "15",
    "op": "TIM",
    "num": "19981064152",
    "wa": "",
    "resp": "Lucas",
    "cpf": "",
    "nasc": "",
    "senha": "4522",
    "cliente": "Toca",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": "Toca paga junto com a namorada"
  },
  {
    "id": 8,
    "v": "10",
    "op": "TIM",
    "num": "19981073124",
    "wa": "",
    "resp": "Val",
    "cpf": "",
    "nasc": "",
    "senha": "4000",
    "cliente": "Bola",
    "base": 80,
    "desc": 15,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 9,
    "v": "10",
    "op": "TIM",
    "num": "19982188420",
    "wa": "",
    "resp": "Rodi",
    "cpf": "",
    "nasc": "",
    "senha": "1466",
    "cliente": "Rodi",
    "base": 100,
    "desc": 0,
    "custo": 50,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 10,
    "v": "10",
    "op": "TIM",
    "num": "19982261949",
    "wa": "",
    "resp": "Breno",
    "cpf": "",
    "nasc": "",
    "senha": "4993",
    "cliente": "Breno",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 11,
    "v": "10",
    "op": "TIM",
    "num": "19982262162",
    "wa": "",
    "resp": "Matheus",
    "cpf": "",
    "nasc": "",
    "senha": "3010",
    "cliente": "Matheus",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 12,
    "v": "10",
    "op": "TIM",
    "num": "19981064153",
    "wa": "",
    "resp": "Antony",
    "cpf": "",
    "nasc": "",
    "senha": "6895",
    "cliente": "Antony",
    "base": 80,
    "desc": 0,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 13,
    "v": "10",
    "op": "TIM",
    "num": "19981311521",
    "wa": "",
    "resp": "Maguila",
    "cpf": "",
    "nasc": "",
    "senha": "8628",
    "cliente": "Mãe dele",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 14,
    "v": "10",
    "op": "TIM",
    "num": "19983612340",
    "wa": "",
    "resp": "Ana",
    "cpf": "",
    "nasc": "",
    "senha": "1152",
    "cliente": "Jhon",
    "base": 115,
    "desc": 0,
    "custo": 50,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 15,
    "v": "10",
    "op": "TIM",
    "num": "19981187937",
    "wa": "",
    "resp": "Dirceu",
    "cpf": "",
    "nasc": "",
    "senha": "1170",
    "cliente": "Grandão",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 16,
    "v": "10",
    "op": "TIM",
    "num": "19982620880",
    "wa": "",
    "resp": "Sandrinho",
    "cpf": "",
    "nasc": "",
    "senha": "4045",
    "cliente": "Sandrinho",
    "base": 80,
    "desc": 25,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 17,
    "v": "15",
    "op": "TIM",
    "num": "19983452887",
    "wa": "",
    "resp": "Namorada do Toca",
    "cpf": "",
    "nasc": "",
    "senha": "7033",
    "cliente": "Namorada do Toca",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": "Toca paga junto"
  },
  {
    "id": 18,
    "v": "10",
    "op": "TIM",
    "num": "19983892145",
    "wa": "",
    "resp": "Evanildo",
    "cpf": "",
    "nasc": "",
    "senha": "3188",
    "cliente": "Evanildo",
    "base": 80,
    "desc": 15,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 19,
    "v": "10",
    "op": "TIM",
    "num": "19981115083",
    "wa": "",
    "resp": "Paçoca",
    "cpf": "",
    "nasc": "",
    "senha": "9062",
    "cliente": "Paçoca",
    "base": 80,
    "desc": 5,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 20,
    "v": "15",
    "op": "TIM",
    "num": "19981720097",
    "wa": "",
    "resp": "Ricardo Alecrim",
    "cpf": "",
    "nasc": "",
    "senha": "7934",
    "cliente": "Ricardo Alecrim",
    "base": 80,
    "desc": 0,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 21,
    "v": "20",
    "op": "TIM",
    "num": "19981743413",
    "wa": "",
    "resp": "Rodi",
    "cpf": "",
    "nasc": "",
    "senha": "1198",
    "cliente": "Val",
    "base": 100,
    "desc": 0,
    "custo": 50,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 22,
    "v": "",
    "op": "TIM",
    "num": "19981906228",
    "wa": "",
    "resp": "Erick",
    "cpf": "",
    "nasc": "",
    "senha": "7342",
    "cliente": "Erick",
    "base": 0,
    "desc": 0,
    "custo": 20,
    "abat": 0,
    "status": "Uso próprio",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 23,
    "v": "",
    "op": "TIM",
    "num": "19982259909",
    "wa": "",
    "resp": "Erick",
    "cpf": "",
    "nasc": "",
    "senha": "3317",
    "cliente": "Erick",
    "base": 0,
    "desc": 0,
    "custo": 20,
    "abat": 0,
    "status": "Uso próprio",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 24,
    "v": "",
    "op": "TIM",
    "num": "19981064176",
    "wa": "",
    "resp": "Poly",
    "cpf": "",
    "nasc": "",
    "senha": "1879",
    "cliente": "Poly",
    "base": 0,
    "desc": 0,
    "custo": 20,
    "abat": 0,
    "status": "Uso próprio",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 25,
    "v": "",
    "op": "TIM",
    "num": "19981055921",
    "wa": "",
    "resp": "Poly",
    "cpf": "",
    "nasc": "",
    "senha": "9045",
    "cliente": "Poly",
    "base": 0,
    "desc": 0,
    "custo": 20,
    "abat": 0,
    "status": "Uso próprio",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 26,
    "v": "01",
    "op": "VIVO",
    "num": "(75) 99804-2680",
    "wa": "",
    "resp": "João",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "João",
    "base": 120,
    "desc": 0,
    "custo": 60,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 27,
    "v": "10",
    "op": "VIVO",
    "num": "(75) 99973-0601",
    "wa": "",
    "resp": "Jorge",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "Jorge",
    "base": 120,
    "desc": 0,
    "custo": 60,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 28,
    "v": "20",
    "op": "VIVO",
    "num": "",
    "wa": "",
    "resp": "Sogra",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "Sogra",
    "base": 120,
    "desc": 0,
    "custo": 60,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": "Número pendente"
  },
  {
    "id": 29,
    "v": "20",
    "op": "VIVO",
    "num": "19996933669",
    "wa": "",
    "resp": "Evaldo",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "Evaldo",
    "base": 120,
    "desc": 70,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 30,
    "v": "",
    "op": "VIVO",
    "num": "(75) 99705-3391",
    "wa": "",
    "resp": "Poly",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "Poly",
    "base": 0,
    "desc": 0,
    "custo": 60,
    "abat": 0,
    "status": "Uso próprio",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 31,
    "v": "",
    "op": "VIVO",
    "num": "(75) 99805-7517",
    "wa": "",
    "resp": "",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "",
    "base": 0,
    "desc": 0,
    "custo": 60,
    "abat": 0,
    "status": "Linha parada",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 32,
    "v": "10",
    "op": "CLARO",
    "num": "19997221999",
    "wa": "",
    "resp": "Nelson",
    "cpf": "",
    "nasc": "",
    "senha": "",
    "cliente": "Nelson",
    "base": 50,
    "desc": 0,
    "custo": 30,
    "abat": 0,
    "status": "Cliente ativo",
    "pago": "Pendente",
    "dataPg": "",
    "obs": ""
  },
  {
    "id": 33,
    "v": "01",
    "op": "SEM OPERADORA",
    "num": "38991150071",
    "wa": "",
    "resp": "Mãe",
    "cpf": "",
    "nasc": "",
    "senha": "7699",
    "cliente": "Vó",
    "base": 0,
    "desc": 0,
    "custo": 30,
    "abat": 0,
    "status": "Custo interno",
    "pago": "Pendente",
    "dataPg": "",
    "obs": "Só custo"
  }
];
